groups:
    - name: fastapi_alerts
      rules:
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"4..|5.."}[5m]) > 0.1
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: "Taux d'erreur élevé"
                description: "Le taux d'erreur HTTP est supérieur à 10% depuis 5 minutes"

          - alert: HighResponseTime
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: "Temps de réponse élevé"
                description: "Le temps de réponse 95e percentile est supérieur à 2 secondes"

          - alert: ServiceDown
            expr: up{job="fastapi-app"} == 0
            for: 1m
            labels:
                severity: critical
            annotations:
                summary: "Service FastAPI indisponible"
                description: "L'application FastAPI n'est pas accessible"

          - alert: HighRequestRate
            expr: rate(http_requests_total[5m]) > 100
            for: 2m
            labels:
                severity: info
            annotations:
                summary: "Taux de requêtes élevé"
                description: "Plus de 100 requêtes par seconde détectées"

    - name: postgresql_alerts
      rules:
          - alert: PostgreSQLHighConnections
            expr: pg_stat_database_numbackends > 80
            for: 2m
            labels:
                severity: warning
            annotations:
                summary: "Nombre de connexions PostgreSQL élevé"
                description: "Plus de 80 connexions actives sur PostgreSQL"

          - alert: PostgreSQLLowCacheHitRatio
            expr: rate(pg_stat_database_blks_hit[5m]) / (rate(pg_stat_database_blks_hit[5m]) + rate(pg_stat_database_blks_read[5m])) < 0.8
            for: 5m
            labels:
                severity: warning
            annotations:
                summary: "Cache hit ratio PostgreSQL faible"
                description: "Le cache hit ratio est inférieur à 80%"

          - alert: PostgreSQLExporterDown
            expr: up{job="postgres-exporter"} == 0
            for: 1m
            labels:
                severity: critical
            annotations:
                summary: "Exporter PostgreSQL indisponible"
                description: "L'exporter PostgreSQL n'est pas accessible"
