global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
    - "alerts.yml"

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "fastapi-app"
      static_configs:
          - targets: ["web:8000"]
      metrics_path: "/metrics"
      scrape_interval: 10s

    - job_name: "postgres-exporter"
      static_configs:
          - targets: ["postgres-exporter:9187"]
      scrape_interval: 30s

    - job_name: "node-exporter"
      static_configs:
          - targets: ["node-exporter:9100"]
      scrape_interval: 15s
