"""empty message

Revision ID: 144064ceef84
Revises: a1b2c3d4e5f6
Create Date: 2025-08-11 13:05:58.964306
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144064ceef84'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


