version: "3.9"

services:
    vanna:
        build: ./
        container_name: vanna
        env_file:
            - .env
        environment:
            POSTGRES_HOST: gmao-postgres-prod
            POSTGRES_PORT: 5432
        ports:
            - "8084:8084"
        restart: unless-stopped
        networks:
            - test_default

networks:
    test_default:
        external: true

