version: '3.8'

services:
  # Base de données PostgreSQL pour le développement
  postgres-dev:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_DB: taskmanager_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d taskmanager_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - dev-network

  # Application FastAPI pour le développement
  fastapi-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_password@postgres-dev:5432/taskmanager_dev
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./app:/app
      - ./alembic:/app/alembic
      - ./logs:/app/logs
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - dev-network
    restart: unless-stopped

  pgadmin-dev:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - dev-network

volumes:
  postgres_dev_data:

networks:
  dev-network:
    driver: bridge 