global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'taskmanager-api-dev'
    static_configs:
      - targets: ['fastapi-dev:8000']
    metrics_path: '/metrics/'
    scrape_interval: 5s

  - job_name: 'taskmanager-api-prod'
    static_configs:
      - targets: ['fastapi-prod:8000']
    metrics_path: '/metrics/'
    scrape_interval: 5s 