apiVersion: 1

policies:
    - orgId: 1
      receiver: discord-default
      group_by:
          - alertname
          - severity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      routes:
          - receiver: discord-default
            object_matchers:
                - [severity, =, critical]
