apiVersion: 1

groups:
    - orgId: 1
      name: fastapi_alerts_grafana
      folder: FastAPI
      interval: 1m
      rules:
          - uid: high-error-rate
            title: HighErrorRate
            condition: A
            data:
                - refId: A
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: prometheus
                  model:
                      editorMode: code
                      expr: rate(http_requests_total{status=~"4..|5.."}[5m]) > 0.1
                      instant: false
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: A
            noDataState: NoData
            execErrState: Error
            for: 2m
            annotations:
                summary: "Taux d'erreur élevé"
                description: "Le taux d'erreur HTTP est supérieur à 10% depuis 5 minutes"
            labels:
                severity: warning

          - uid: high-response-time
            title: HighResponseTime
            condition: A
            data:
                - refId: A
                  relativeTimeRange:
                      from: 300
                      to: 0
                  datasourceUid: prometheus
                  model:
                      editorMode: code
                      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
                      instant: false
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: A
            noDataState: NoData
            execErrState: Error
            for: 2m
            annotations:
                summary: "Temps de réponse élevé"
                description: "Le temps de réponse 95e percentile est supérieur à 2 secondes"
            labels:
                severity: warning

          - uid: service-down
            title: ServiceDown
            condition: A
            data:
                - refId: A
                  relativeTimeRange:
                      from: 60
                      to: 0
                  datasourceUid: prometheus
                  model:
                      editorMode: code
                      expr: up{job="fastapi-app"} == 0
                      instant: false
                      intervalMs: 1000
                      maxDataPoints: 43200
                      refId: A
            noDataState: NoData
            execErrState: Error
            for: 1m
            annotations:
                summary: "Service FastAPI indisponible"
                description: "L'application FastAPI n'est pas accessible"
            labels:
                severity: critical
