"""modification demande matériel

Revision ID: 2717c6b6e1f8
Revises: 001
Create Date: 2025-06-24 07:26:19.843205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2717c6b6e1f8'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandes', sa.Column('table_atelier', sa.String(length=200), nullable=False))
    op.add_column('demandes', sa.Column('id_table', sa.String(length=20), nullable=True))
    op.add_column('demandes', sa.Column('reference_produit', sa.String(length=20), nullable=False))
    op.add_column('demandes', sa.Column('designation_produit', sa.String(length=500), nullable=True))
    op.add_column('demandes', sa.Column('quantite_demandee', sa.Integer(), nullable=False))
    op.add_column('demandes', sa.Column('unite', sa.String(length=50), nullable=True))
    op.add_column('demandes', sa.Column('fournisseur', sa.String(length=200), nullable=True))
    op.add_column('demandes', sa.Column('emplacement', sa.String(length=500), nullable=True))
    op.alter_column('demandes', 'date_demande',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_demandes_id_table'), 'demandes', ['id_table'], unique=False)
    op.create_index(op.f('ix_demandes_reference_produit'), 'demandes', ['reference_produit'], unique=False)
    op.create_index(op.f('ix_demandes_table_atelier'), 'demandes', ['table_atelier'], unique=False)
    op.drop_column('demandes', 'motif')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandes', sa.Column('motif', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_demandes_table_atelier'), table_name='demandes')
    op.drop_index(op.f('ix_demandes_reference_produit'), table_name='demandes')
    op.drop_index(op.f('ix_demandes_id_table'), table_name='demandes')
    op.alter_column('demandes', 'date_demande',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('demandes', 'emplacement')
    op.drop_column('demandes', 'fournisseur')
    op.drop_column('demandes', 'unite')
    op.drop_column('demandes', 'quantite_demandee')
    op.drop_column('demandes', 'designation_produit')
    op.drop_column('demandes', 'reference_produit')
    op.drop_column('demandes', 'id_table')
    op.drop_column('demandes', 'table_atelier')
    # ### end Alembic commands ### 