"""add_id_demande_base_field

Revision ID: c203934c5739
Revises: 2717c6b6e1f8
Create Date: 2025-06-24 08:27:46.139211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c203934c5739'
down_revision = '2717c6b6e1f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Étape 1: Ajouter la colonne comme nullable
    op.add_column('demandes', sa.Column('id_demande_base', sa.String(length=50), nullable=True))
    
    # Étape 2: Remplir les valeurs existantes avec id_demande pour les demandes existantes
    op.execute("UPDATE demandes SET id_demande_base = id_demande WHERE id_demande_base IS NULL")
    
    # Étape 3: Rendre la colonne non-nullable
    op.alter_column('demandes', 'id_demande_base', nullable=False)
    
    # Étape 4: Créer l'index
    op.create_index(op.f('ix_demandes_id_demande_base'), 'demandes', ['id_demande_base'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demandes_id_demande_base'), table_name='demandes')
    op.drop_column('demandes', 'id_demande_base')
    # ### end Alembic commands ### 