"""empty message

Revision ID: fad4ac93cb98
Revises: c203934c5739
Create Date: 2025-06-24 12:50:03.415631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad4ac93cb98'
down_revision = 'c203934c5739'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparations_demandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_demande_base', sa.String(length=50), nullable=False),
    sa.Column('statut_preparation', sa.String(length=50), nullable=True),
    sa.Column('prepare_par', sa.String(length=200), nullable=True),
    sa.Column('date_debut_preparation', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_validation_preparation', sa.TIMESTAMP(), nullable=True),
    sa.Column('date_livraison', sa.TIMESTAMP(), nullable=True),
    sa.Column('nb_produits_total', sa.Integer(), nullable=False),
    sa.Column('nb_produits_scannes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparations_demandes_id'), 'preparations_demandes', ['id'], unique=False)
    op.create_index(op.f('ix_preparations_demandes_id_demande_base'), 'preparations_demandes', ['id_demande_base'], unique=True)
    op.create_index(op.f('ix_preparations_demandes_statut_preparation'), 'preparations_demandes', ['statut_preparation'], unique=False)
    op.create_table('produits_scannes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preparation_id', sa.Integer(), nullable=False),
    sa.Column('reference_produit', sa.String(length=20), nullable=False),
    sa.Column('date_scan', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('scanne_par', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['preparation_id'], ['preparations_demandes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_scannes_id'), 'produits_scannes', ['id'], unique=False)
    op.create_index(op.f('ix_produits_scannes_reference_produit'), 'produits_scannes', ['reference_produit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produits_scannes_reference_produit'), table_name='produits_scannes')
    op.drop_index(op.f('ix_produits_scannes_id'), table_name='produits_scannes')
    op.drop_table('produits_scannes')
    op.drop_index(op.f('ix_preparations_demandes_statut_preparation'), table_name='preparations_demandes')
    op.drop_index(op.f('ix_preparations_demandes_id_demande_base'), table_name='preparations_demandes')
    op.drop_index(op.f('ix_preparations_demandes_id'), table_name='preparations_demandes')
    op.drop_table('preparations_demandes')
    # ### end Alembic commands ### 