version: "3.9"

services:
    ftp:
        image: fauria/vsftpd
        container_name: ftp_server
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        environment:
            - FTP_USER=${FTP_USER}
            - FTP_PASS=${FTP_PASS}
            - PASV_ADDRESS=${PASV_ADDRESS}
            - PASV_MIN_PORT=${PASV_MIN_PORT}
            - PASV_MAX_PORT=${PASV_MAX_PORT}
        volumes:
            - ./logs:/home/vsftpd/${FTP_USER}
        restart: unless-stopped

    db:
        image: postgres:15
        container_name: postgres_db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: unless-stopped

    api:
        build: ./api
        container_name: fastapi_server
        depends_on:
            - db
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "8000:8000"
        volumes:
            - ./api:/app
        restart: unless-stopped

    ui:
        build: ./UI
        container_name: streamlit_ui
        depends_on:
            - api
        ports:
            - "8501:8501"
        volumes:
            - ./UI:/app
        restart: unless-stopped

    parser:
        build: ./script
        container_name: log_parser
        depends_on:
            - ftp
            - db
        environment:
            - FTP_HOST=ftp
            - FTP_USER=${FTP_USER}
            - FTP_PASS=${FTP_PASS}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./script:/app
        restart: unless-stopped

volumes:
    pgdata:
