name: CI/CD Pipeline

on:
    push:
        branches: [main, master, develop, feature/*]
    pull_request:
        branches: [main, master]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Cache pip dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('E3-E4/fastapi/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r E3/fastapi/requirements.txt

            - name: Run tests with pytest
              env:
                  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
                  SECRET_KEY: test_secret_key_for_ci
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
              run: |
                  cd E3/fastapi
                  pytest tests/ -v --cov=. --cov-report=term-missing --cov-report=html:htmlcov

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-reports
                  path: E3-E4/fastapi/htmlcov/
                  retention-days: 30
